# Generated by Django 4.0.3 on 2022-08-16 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True, help_text='Best applications, further explanation, etc.', null=True)),
                ('slug', models.SlugField(editable=False)),
            ],
            options={
                'ordering': ['abbreviation'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True, help_text='Best applications, further explanation, etc.', null=True)),
                ('slug', models.SlugField(editable=False)),
            ],
            options={
                'ordering': ['abbreviation'],
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(editable=False)),
                ('website', models.URLField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('designation', models.CharField(help_text='e.g. \'T\' for "Triangle"', max_length=20)),
                ('slug', models.SlugField(editable=False)),
            ],
            options={
                'ordering': ['name', 'designation'],
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(blank=True, help_text='Manufacturer or Vendor Number', max_length=50, null=True, unique=True)),
                ('description', models.TextField()),
                ('slug', models.SlugField(editable=False)),
                ('website', models.URLField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tool_compatibility.manufacturer')),
            ],
            options={
                'ordering': ['part_number'],
            },
        ),
        migrations.CreateModel(
            name='Holder',
            fields=[
                ('tool_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tool_compatibility.tool')),
                ('designation', models.CharField(help_text='e.g. SER0500H11', max_length=50, unique=True)),
                ('machine_type', models.CharField(choices=[('Milling', (('any_vertical', 'Vertical Mill (CNC or Manual)'), ('any', 'Any Mill (Vertical or Horizontal'), ('vertical_mill', 'Vertical Mill - Manual'), ('horizontal_mill', 'Horizontal Mill'), ('vertical_machining_center', 'Vertical Machining Center - CNC'))), ('Turning', (('any_cnc', 'Any CNC'), ('any', 'Any Lathe'), ('engine_lathe', 'Engine Lathe - Manual'), ('slant_bed_cnc', 'Slant Bed - CNC')))], default='any_vertical', max_length=30)),
            ],
            options={
                'ordering': ['designation', 'description'],
            },
            bases=('tool_compatibility.tool',),
        ),
        migrations.CreateModel(
            name='Insert',
            fields=[
                ('tool_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tool_compatibility.tool')),
                ('package_quantity', models.IntegerField(blank=True, null=True)),
                ('designation', models.CharField(help_text='e.g. 11IRA60', max_length=50, unique=True)),
                ('size', models.CharField(blank=True, max_length=30, null=True)),
                ('thickness', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('application', models.CharField(blank=True, help_text='Internal/External/etc.', max_length=50, null=True)),
                ('hand', models.CharField(blank=True, help_text='Left/Right/Neutral', max_length=15, null=True)),
                ('corner_radius', models.CharField(blank=True, max_length=15, null=True)),
                ('miscellaneous', models.TextField(blank=True, help_text='e.g. pitch range, finish, preferred application', null=True)),
            ],
            bases=('tool_compatibility.tool',),
        ),
        migrations.AddConstraint(
            model_name='shape',
            constraint=models.UniqueConstraint(fields=('name', 'designation'), name='unique_insert_shape'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insert',
            name='coating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tool_compatibility.coating'),
        ),
        migrations.AddField(
            model_name='insert',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tool_compatibility.grade'),
        ),
        migrations.AddField(
            model_name='insert',
            name='holder',
            field=models.ManyToManyField(to='tool_compatibility.holder'),
        ),
        migrations.AddField(
            model_name='insert',
            name='shape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tool_compatibility.shape'),
        ),
    ]
