# Generated by Django 4.0.3 on 2022-08-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool_compatibility', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tool',
            name='part_number',
            field=models.CharField(blank=True, default='', help_text='Manufacturer or Vendor Number', max_length=50),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='tool',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'part_number'), name='unique_tool'),
        ),
    ]
