# Generated by Django 4.0.3 on 2022-05-18 16:55

from django.db import migrations, models
import purchases.models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0008_alter_purchaserequest_purchase_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of Carrier')),
                ('tracking_link', models.URLField(verbose_name='URL stub for tracking')),
                ('website', models.URLField(verbose_name='Carrier Website')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tax_exempt',
            field=models.BooleanField(default=False, verbose_name='Tax Exempt?'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=purchases.models.Carrier, to='purchases.carrier'),
        ),
    ]
