# Generated by Django 4.0.3 on 2022-05-18 16:58

from django.db import migrations, models
import purchases.models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0009_carrier_state_product_tax_exempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='state',
            field=models.ForeignKey(null=True, on_delete=purchases.models.State, to='purchases.state'),
        ),
    ]
