# Generated by Django 4.0.3 on 2022-05-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0012_vendor_slug_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=255, unique=True),
        ),
    ]
