# Generated by Django 4.0.3 on 2022-05-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0018_alter_accounts_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='sales_tax',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='subtotal',
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='purchaserequestitems',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=14),
        ),
    ]
