# Generated by Django 4.0.3 on 2022-05-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0019_remove_purchaserequest_grand_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=255),
        ),
    ]
