# Generated by Django 4.0.3 on 2022-05-20 20:13

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0024_purchaserequest_accounts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaserequestaccounts',
            options={'verbose_name_plural': 'Purchase Request Accounts'},
        ),
        migrations.AlterModelOptions(
            name='spendcategory',
            options={'verbose_name_plural': 'Spend Categories'},
        ),
        migrations.AlterField(
            model_name='requisitioner',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=10, region=None, verbose_name='Phone Number'),
        ),
    ]
