# Generated by Django 4.0.3 on 2022-05-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0026_vendor_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=25)),
                ('abbreviation', models.CharField(max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='purchaserequestitems',
            name='unit',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='gift',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='grant',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
