# Generated by Django 4.0.8 on 2023-01-30 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0070_auto_20230119_1522'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.SmallIntegerField(editable=False, verbose_name='in project ordering')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='purchase_requests',
            field=models.ManyToManyField(through='projects.ProjectPurchaseRequest', to='purchases.purchaserequest', verbose_name='purchase requests'),
        ),
        migrations.AddField(
            model_name='projectpurchaserequest',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='project'),
        ),
        migrations.AddField(
            model_name='projectpurchaserequest',
            name='purchase_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.purchaserequest', verbose_name='purchase request'),
        ),
    ]
