# Generated by Django 4.0.8 on 2023-01-31 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0070_auto_20230119_1522'),
        ('projects', '0002_projectpurchaserequest_project_purchase_requests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='purchase_requests',
            field=models.ManyToManyField(blank=True, through='projects.ProjectPurchaseRequest', to='purchases.purchaserequest', verbose_name='purchase requests'),
        ),
    ]
