[tool.black]
    extend-exclude = '(/migrations|apps.py| *sgi.py|__init__.py| *urls.py)'

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
default_section = "THIRDPARTY"
known_first_party = ["api", "user"]
known_third_party = ["furl", "benedict", "django_listview_filters"]
