[tool.black]
extend-exclude = '(/migrations|apps.py| *sgi.py|__init__.py| *urls.py)'
# line-lengh = 88
target-version = ['py310']

# [tool.isort]
# profile = "black"
# multi_line_output = 3
# line_length = 88
# skip_glob = ["migrations/"]
# # extend_skip_glob = ["migrations/"]
# default_section = "THIRDPARTY"
# known_first_party = ["api", "user"]
# known_third_party = ["furl", "benedict", "django_listview_filters"]

[tool.djlint]
profile = "django"

[tool.ruff]
extend-exclude = ["migrations"]
ignore = ["T20"]
line-length = 88
select = ["C9", "E", "F", "T2", "W"]
ignore-init-module-imports = true
target-version = "py310"

[tool.ruff.mccabe]
max-complexity = 10
