[tool.black]
extend-exclude = '(/migrations|apps.py| *sgi.py|__init__.py| *urls.py)'
# line-lengh = 88
target-version = ['py310']

# [tool.isort]
# profile = "black"
# multi_line_output = 3
# line_length = 88
# skip_glob = ["migrations/"]
# # extend_skip_glob = ["migrations/"]
# default_section = "THIRDPARTY"
# known_first_party = ["api", "user"]
# known_third_party = ["furl", "benedict", "django_listview_filters"]

[tool.djlint]
profile = "django"

[tool.ruff]
extend-exclude = ["migrations"]
ignore = ["T20"]
fixable = ["E", "COM812", "I001", "UP032", "UP035"]
unfixable = ["F841"]
line-length = 88
select = [
    "B",
    "C4",
    "C9",
    "COM",
    # "DJ",
    "E",
    "F",
    "I",
    "T2",
    "W",
    "N",
    "PTH",
    "Q",
    # "RET",
    "S",
    "SIM",
    "TD",
    "TID",
    "UP",
]
ignore-init-module-imports = true
target-version = "py310"

[tool.ruff.mccabe]
max-complexity = 10
