# Generated by Django 4.0.9 on 2023-02-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='setting name')),
                ('helper_text', models.TextField(blank=True, verbose_name='explanatory text')),
                ('data_type', models.CharField(choices=[('FLOAT', 'Float'), ('TEXT', 'Text'), ('INT', 'Integer')], default='TEXT', max_length=50, verbose_name='data type')),
                ('value', models.TextField(verbose_name='setting value')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('abbreviation', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
