# Generated by Django 4.0.3 on 2022-09-26 17:18

from django.db import migrations, models

import web_project.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate', web_project.fields.PercentageField(decimal_places=6, max_digits=10, verbose_name='default sales tax rate')),
                ('purchase_request_instructions', models.TextField(verbose_name='default purchase request instructions')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('abbreviation', models.CharField(max_length=2, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
