# Generated by Django 4.0.3 on 2022-09-26 17:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0002_auto_20220926_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defaultvalues',
            name='purchase_request_instructions',
        ),
        migrations.RemoveField(
            model_name='defaultvalues',
            name='tax_rate',
        ),
        migrations.AddField(
            model_name='defaultvalues',
            name='date_type',
            field=models.CharField(choices=[('FLOAT', 'float'), ('TEXT', 'text'), ('INT', 'integer')], default='TEXT', max_length=50, verbose_name='data type'),
        ),
        migrations.AddField(
            model_name='defaultvalues',
            name='helper_text',
            field=models.TextField(blank=True, verbose_name='explanatory text'),
        ),
        migrations.AddField(
            model_name='defaultvalues',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='setting name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='defaultvalues',
            name='value',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='setting value'),
            preserve_default=False,
        ),
    ]
