# Generated by Django 4.0.3 on 2022-09-26 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0003_remove_defaultvalues_purchase_request_instructions_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DefaultValues',
            new_name='DefaultValue',
        ),
    ]
