# Generated by Django 4.0.3 on 2022-09-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globals', '0004_rename_defaultvalues_defaultvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultvalue',
            name='date_type',
            field=models.CharField(choices=[('FLOAT', 'Float'), ('TEXT', 'Text'), ('INT', 'Integer')], default='TEXT', max_length=50, verbose_name='data type'),
        ),
    ]
