# Generated by Django 4.2.2 on 2023-07-03 16:12

from django.db import migrations


def purchase_request_defaults(apps, schema_editor):
    sales_tax_default = 0.087
    instructions_default = "Because grand total amount often does not include shipping/handling or tax costs, Dr. Mo approves if total costs exceed grand total amount."

    DefaultValue = apps.get_model("globals", "DefaultValue")

    sales_tax_rate, created = DefaultValue.objects.get_or_create(
        name="Sales Tax Rate",
        data_type="FLOAT",
        value=sales_tax_default,
    )

    print(f"Sales Tax Rate (Created): {sales_tax_rate.value:.3f} ({created})")

    instructions, created = DefaultValue.objects.get_or_create(
        name="Purchase Request Instructions",
        data_type="TEXT",
        value=instructions_default,
    )

    print(f"Instructions (created): {instructions.value} ({created})")


class Migration(migrations.Migration):
    dependencies = [
        ("globals", "0006_rename_date_type_defaultvalue_data_type"),
    ]

    operations = [
        migrations.RunPython(purchase_request_defaults, migrations.RunPython.noop),
    ]
