# Generated by Django 4.0.3 on 2022-05-25 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup_sheets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setupsheettool',
            options={'ordering': ('position',)},
        ),
        migrations.AddField(
            model_name='setupsheet',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='tool',
            name='tool_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holder', to='setup_sheets.toolcomponents'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='tool_insert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insert', to='setup_sheets.toolcomponents'),
        ),
    ]
