# Generated by Django 4.0.3 on 2022-07-29 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setup_sheets", "0002_part_alter_setupsheet_options_and_more"),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='setupsheet',
        #     name='material',
        # ),
        # migrations.RemoveField(
        #     model_name='setupsheet',
        #     name='part_number',
        # ),
        migrations.RunSQL("DROP TABLE `seas_purchasing`.`setup_sheets_partrevision`;"),
        migrations.CreateModel(
            name="PartRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revision", models.CharField(blank=True, max_length=10)),
                # ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup_sheets.part')),
            ],
        ),
        # migrations.AlterField(
        #     model_name='setupsheet',
        #     name='part_revision',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='setup_sheets.part_revision')
        # ),
        # migrations.RunSQL("DROP TABLE `seas_purchasing`.`setup_sheets_part`;"),
        # migrations.CreateModel(
        #     name='Part',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=150)),
        #         ('number', models.CharField(max_length=50, unique=True)),
        #         ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setup_sheets.material')),
        #     ],
        # ),
        # migrations.AddField(
        #     model_name='setupsheet',
        #     name='part',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='setup_sheets.part'),
        # ),
        # migrations.AlterField(
        #     model_name='setupsheet',
        #     name='part_revision',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='setup_sheets.partrevision'),
        # ),
    ]
