# Generated by Django 4.0.3 on 2022-05-27 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup_sheets', '0002_alter_setupsheettool_options_setupsheet_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Fixture Name')),
                ('part_number', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='setupsheet',
            name='fixture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='setup_sheets.fixture'),
        ),
    ]
