# Generated by Django 4.0.3 on 2022-07-29 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setup_sheets", "0004_alter_setupsheet_options_part_partrevision_part"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE `seas_purchasing`.`setup_sheets_setupsheet` DROP FOREIGN KEY setup_sheets_setupsheet_part_id_78796717_fk_setup_sheets_part_id;"
        ),
        migrations.RunSQL(
            "ALTER TABLE `seas_purchasing`.`setup_sheets_setupsheet` DROP COLUMN `part_id`;"
        ),
        # migrations.RunSQL("ALTER TABLE `seas_purchasing`.`setup_sheets_setupsheet` DROP COLUMN `part_revision_id`;"),
        # migrations.RemoveField(
        #     model_name='setupsheet',
        #     name='part'
        # ),
        # migrations.RemoveField(
        #     model_name='setupsheet',
        #     name='part_revision'
        # ),
        migrations.RunSQL("DROP TABLE `seas_purchasing`.`setup_sheets_part`;"),
        # migrations.AlterModelOptions(
        #     name='setupsheet',
        #     options={'ordering': ['operation']},
        # ),
        # migrations.AlterField(
        #     model_name='setupsheet',
        #     name=''
        # ),
        # migrations.RunSQL("DROP TABLE `seas_purchasing`.`setup_sheets_part`;"),
        # migrations.CreateModel(
        #     name='Part',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('name', models.CharField(max_length=150)),
        #         ('number', models.CharField(max_length=50, unique=True)),
        #         ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='setup_sheets.material')),
        #     ],
        # ),
        # migrations.AddField(
        #     model_name='partrevision',
        #     name='part',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='setup_sheets.part'),
        # ),
    ]
