# Generated by Django 4.0.3 on 2022-07-29 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("setup_sheets", "0004_alter_setupsheet_options_part_partrevision_part"),
    ]

    operations = [
        # migrations.RunSQL("ALTER TABLE `seas_purchasing`.`setup_sheets_setupsheet` ADD part_number CHAR;"),
        # migrations.RunSQL(
        #     "ALTER TABLE `seas_purchasing`.`setup_sheets_setupsheet` ADD part_revision CHAR;"
        # ),
        # migrations.RemoveField(
        #     model_name='setupsheet',
        #     name='part_number',
        # ),
        migrations.RemoveField(
            model_name="setupsheet",
            name="part_revision",
        ),
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("number", models.CharField(max_length=50, unique=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="setup_sheets.material",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="partrevision",
            name="part",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="setup_sheets.part",
            ),
        ),
        migrations.AddField(
            model_name="setupsheet",
            name="part",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="setup_sheets.part",
            ),
        ),
    ]
