# Generated by Django 4.0.3 on 2022-07-29 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup_sheets', '0007_remove_setupsheet_part_number'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE `seas_purchasing`.`setup_sheets_setupsheet` ADD material_id CHAR;"),
        migrations.RemoveField(
            model_name='setupsheet',
            name='material',
        ),
        migrations.RunSQL("ALTER TABLE `seas_purchasing`.`setup_sheets_setupsheet` DROP COLUMN part_revision_id;"),
        migrations.AddField(
            model_name='setupsheet',
            name='part_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='setup_sheets.partrevision'),
        ),
    ]
