# Generated by Django 4.0.3 on 2022-07-29 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup_sheets', '0008_remove_setupsheet_material_setupsheet_part_revision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setupsheet',
            name='part',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='setup_sheets.part'),
        ),
    ]
