# Generated by Django 4.0.3 on 2022-07-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_sheets', '0009_alter_setupsheet_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
