# Generated by Django 4.0.3 on 2022-07-29 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup_sheets', '0011_alter_partrevision_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='slug',
            field=models.SlugField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='partrevision',
            name='part',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='setup_sheets.part'),
            preserve_default=False,
        ),
    ]
