# Generated by Django 4.0.3 on 2022-08-01 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup_sheets', '0012_alter_part_slug_alter_partrevision_part'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['number']},
        ),
        migrations.AlterModelOptions(
            name='partrevision',
            options={'get_latest_by': ['revision'], 'ordering': ['revision']},
        ),
        migrations.AlterModelOptions(
            name='setupsheet',
            options={'ordering': ['part__number', 'operation']},
        ),
    ]
