# Generated by Django 4.0.3 on 2022-08-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_sheets', '0013_alter_part_options_alter_partrevision_options_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='partrevision',
            constraint=models.UniqueConstraint(fields=('part', 'revision'), name='unique_part_revision'),
        ),
    ]
