# Generated by Django 4.2.2 on 2023-07-03 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("purchases", "0074_alter_balance_balance_currency_and_more"),
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="purchases.manufacturer",
                verbose_name="manufacturer",
            ),
        ),
        migrations.AlterField(
            model_name="building",
            name="name",
            field=models.CharField(max_length=150, verbose_name="name"),
        ),
    ]
