# Generated by Django 4.2.2 on 2023-07-03 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assets", "0002_alter_asset_manufacturer_alter_building_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="capital_equipment",
            field=models.BooleanField(
                default=False,
                help_text="must meet conditions",
                verbose_name="capital equipment",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(editable=False, unique=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                ("website", models.URLField(verbose_name="manufacturer website")),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="contact name"
                    ),
                ),
                (
                    "contact_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        region=None,
                        verbose_name="contact phone number",
                    ),
                ),
                (
                    "contact_extension",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="phone extension"
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="contact email"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
