# Generated by Django 4.2.2 on 2023-07-06 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0002_asset_capital_equipment_asset_enumerable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="building",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="assets.building",
                verbose_name="building",
            ),
            preserve_default=False,
        ),
    ]
