# Generated by Django 4.2.2 on 2023-07-03 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0003_asset_capital_equipment_manufacturer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="assets.manufacturer",
                verbose_name="manufacturer",
            ),
        ),
    ]
