# Generated by Django 4.2.2 on 2023-07-03 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("assets", "0005_alter_asset_purchase_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="enumerable",
            field=models.BooleanField(
                default=False,
                help_text='typically used for calipers or other "countable" assets',
                verbose_name="enumerable",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="EnumerableAssetGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(editable=False, unique=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "counter_digits",
                    models.PositiveSmallIntegerField(
                        default=2, verbose_name="number of digits for counter"
                    ),
                ),
                (
                    "next_digit",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="next counter digit"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EnumerableAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(editable=False, unique=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "counter",
                    models.CharField(
                        help_text="padded", max_length=50, verbose_name="group counter"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="assets.asset"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_related",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="assets.enumerableassetgroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="enumerable_asset",
            field=models.ManyToManyField(
                through="assets.EnumerableAsset",
                to="assets.enumerableassetgroup",
                verbose_name="enumerable asset",
            ),
        ),
    ]
