# Generated by Django 4.2.2 on 2023-07-03 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0007_remove_asset_enumerable_asset_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="enumerable_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="assets.enumerableassetgroup",
                verbose_name="enumerable group",
            ),
        ),
    ]
