# Generated by Django 4.0.3 on 2022-03-30 19:12

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import purchases.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=10, verbose_name='Account')),
                ('budget_code', models.CharField(max_length=5, verbose_name='Budget Code')),
                ('fund', models.CharField(max_length=5, verbose_name='Fund')),
                ('program_workday', models.CharField(max_length=10, verbose_name='Program Workday')),
                ('account_title', models.CharField(max_length=200, verbose_name='Account Title')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='Code/Abbreviation')),
                ('name', models.CharField(max_length=150, verbose_name='Full Department Name')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of Manufacturer')),
                ('website', models.URLField(blank=True, verbose_name='URL of Manufacturer')),
                ('wsu_discount', models.BooleanField(default=False, verbose_name='Does WSU get a discount?')),
                ('created_date', models.DateTimeField(verbose_name='Date manufacturer added')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Manufacturer Phone Number (optional)')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of Product')),
                ('description', models.TextField(verbose_name='Description of product')),
                ('created_date', models.DateTimeField(verbose_name='Date Product Created')),
                ('specification', models.TextField(verbose_name='Detailed Specifications (required if no specification sheet)')),
                ('spec_sheet', models.FileField(blank=True, upload_to='products', verbose_name='Specifications')),
                ('substitution', models.CharField(choices=[('buyers_choice', 'Substitute with like product'), ('strict', 'No substitutions allowed'), ('ask_before', 'Ask before substituting')], default='buyers_choice', max_length=150, verbose_name='Product Replacement')),
                ('last_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Last Price')),
                ('original_manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of Vendor')),
                ('wsu_discount', models.BooleanField(default=False, verbose_name='Does WSU get a discount?')),
                ('website', models.URLField(verbose_name='URL/Link to Vendor Website')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Vendor Phone Number')),
                ('street1', models.CharField(max_length=50, verbose_name='Address 1')),
                ('street2', models.CharField(blank=True, max_length=50, verbose_name='Address 2 (optional)')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('zip', models.CharField(max_length=10, verbose_name='ZIP Code')),
            ],
        ),
        migrations.CreateModel(
            name='Requisitioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('phone', models.CharField(max_length=10, verbose_name='Phone Number')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.department')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=10, unique=True)),
                ('created_date', models.DateTimeField(verbose_name='Created Date')),
                ('need_by_date', models.DateField(blank=True, verbose_name='Date Required (optional)')),
                ('tax_exempt', models.BooleanField(default=False, verbose_name='Tax Exempt?')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('shipping', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Shipping ($)')),
                ('sales_tax', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sales Tax ($)')),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Grand Total ($)')),
                ('justification', models.TextField(verbose_name='Justification')),
                ('instruction', models.TextField(default='Because grand total amount does not include shipping/handling and tax costs, Dr. Mo approves if total costs exceeds grand total amount.', verbose_name='Special Instructions')),
                ('purchase_type', models.CharField(choices=[('po', 'PURCHASE ORDER'), ('pcard', 'PCARD'), ('iri', 'IRI'), ('invoice voucher', 'INVOICE VOUCHER'), ('contract', 'CONTRACT')], default='PCARD', max_length=150, verbose_name='Choose One')),
                ('accounts', models.ManyToManyField(to='purchases.accounts')),
                ('products', models.ManyToManyField(to='purchases.product')),
                ('requisitioner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.requisitioner')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=10, unique=True)),
                ('created_date', models.DateTimeField(verbose_name='Created Date')),
                ('tax_exempt', models.BooleanField(default=False, verbose_name='Tax Exempt?')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('shipping', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Shipping ($)')),
                ('sales_tax', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Sales Tax ($)')),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Grand Total ($)')),
                ('vendor', models.ForeignKey(on_delete=purchases.models.Vendor, to='purchases.vendor')),
            ],
        ),
    ]
