# Generated by Django 4.0.3 on 2022-03-30 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='approved_substitutes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='purchases.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='approved_vendors',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchases.vendor'),
        ),
    ]
