# Generated by Django 4.0.3 on 2022-06-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, upload_to='products', verbose_name='Product Image (options)'),
        ),
    ]
