# Generated by Django 4.0.3 on 2022-03-30 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_product_approved_substitutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='discount_percentage',
            field=models.FloatField(default=0),
        ),
    ]
