# Generated by Django 4.0.3 on 2022-06-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='slug',
            field=models.CharField(default='ups', max_length=10, verbose_name='Carrier Slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tracking_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, upload_to='products', verbose_name='Product Image (optional)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='spec_sheet',
            field=models.FileField(blank=True, upload_to='products', verbose_name='Specification Sheet'),
        ),
    ]
