# Generated by Django 4.0.3 on 2022-06-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_carrier_slug_purchaseorder_tracking_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='tracker_created',
            field=models.BooleanField(default=True),
        ),
    ]
