# Generated by Django 4.0.3 on 2022-03-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_manufacturer_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='discount_percentage',
            field=models.FloatField(default=0),
        ),
    ]
