# Generated by Django 4.0.3 on 2022-06-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_purchaseorder_tracker_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='shipping_status',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='tracker_created',
            field=models.BooleanField(default=False),
        ),
    ]
