# Generated by Django 4.0.3 on 2022-03-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_vendor_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date manufacturer added'),
        ),
    ]
