# Generated by Django 4.0.3 on 2022-06-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_purchaseorder_shipping_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='tracker_active',
            field=models.BooleanField(default=True),
        ),
    ]
