# Generated by Django 4.0.3 on 2022-06-09 20:22

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_purchaseorder_tracker_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingWebhookMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(help_text='DateTime that message was recieved.')),
                ('payload', models.JSONField(default=None, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='requisitioner',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=25, null=True, region=None, verbose_name='Phone Number'),
        ),
        migrations.AddIndex(
            model_name='trackingwebhookmessage',
            index=models.Index(fields=['received_at'], name='purchases_t_receive_ab53e7_idx'),
        ),
    ]
