# Generated by Django 4.0.3 on 2022-04-01 22:32

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0006_product_identifier_product_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='approved_substitutes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='purchases.product'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Vendor Phone Number'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='state',
            field=models.CharField(blank=True, max_length=50, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='street1',
            field=models.CharField(blank=True, max_length=50, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='zip',
            field=models.CharField(blank=True, max_length=10, verbose_name='ZIP Code'),
        ),
    ]
