# Generated by Django 4.0.3 on 2022-05-05 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_alter_product_approved_substitutes_alter_vendor_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='purchase_type',
            field=models.CharField(choices=[('po', 'PURCHASE ORDER'), ('pcard', 'PCARD'), ('iri', 'IRI'), ('invoice voucher', 'INVOICE VOUCHER'), ('contract', 'CONTRACT')], default='pcard', max_length=150, verbose_name='Choose One'),
        ),
        migrations.CreateModel(
            name='PurchaseRequestItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=3)),
                ('unit', models.CharField(choices=[('each', 'Each'), ('kit', 'Kit'), ('pack', 'Pack'), ('ft', 'ft'), ('in', 'in'), ('meters', 'meters'), ('mm', 'mm'), ('lbs', 'pounds'), ('gallons', 'gallons')], default='each', max_length=30, verbose_name='Choose One')),
                ('pr_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.purchaserequest')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.product')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=3)),
                ('unit', models.CharField(choices=[('each', 'Each'), ('kit', 'Kit'), ('pack', 'Pack'), ('ft', 'ft'), ('in', 'in'), ('meters', 'meters'), ('mm', 'mm'), ('lbs', 'pounds'), ('gallons', 'gallons')], default='each', max_length=30, verbose_name='Choose One')),
                ('pr_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.purchaseorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.product')),
            ],
        ),
    ]
