# Generated by Django 4.0.3 on 2022-06-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0007_trackingwebhookmessage_alter_requisitioner_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='tracker_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
