# Generated by Django 4.0.3 on 2022-06-14 23:20

from django.db import migrations, models
import purchases.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0009_manufacturer_mfg_logo_alter_purchaseorder_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete= purchases.models.models_metadata.Carrier, to='purchases.carrier'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='shipping_status',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='shipping_status_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='tracker_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='slug',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Carrier Slug'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='tracking_link',
            field=models.URLField(blank=True, verbose_name='URL stub for tracking'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='website',
            field=models.URLField(blank=True, verbose_name='Carrier Website'),
        ),
    ]
