# Generated by Django 4.0.3 on 2022-06-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0011_remove_purchaserequest_shipping_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='shipment_id',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tracker',
            name='status',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
