# Generated by Django 4.0.3 on 2022-05-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0016_alter_manufacturer_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderitems',
            old_name='pr_number',
            new_name='purchase_order',
        ),
        migrations.RenameField(
            model_name='purchaserequestitems',
            old_name='pr_number',
            new_name='purchase_request',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='products',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='items',
            field=models.ManyToManyField(through='purchases.PurchaseRequestItems', to='purchases.product'),
        ),
    ]
