# Generated by Django 4.0.3 on 2022-06-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0016_alter_tracker_delivery_estimate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='delivery_estimate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
