# Generated by Django 4.0.3 on 2022-05-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0017_rename_pr_number_purchaseorderitems_purchase_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='purchaserequestitems',
            options={'verbose_name_plural': 'Purchase Request Items'},
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='need_by_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date Required (optional)'),
        ),
    ]
