# Generated by Django 4.0.3 on 2022-06-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0018_alter_product_spec_sheet_alter_product_specification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequestaccounts',
            name='distribution_type',
            field=models.CharField(choices=[('percent', 'Percent'), ('amount', 'Amount')], default='percent', max_length=15),
        ),
    ]
