# Generated by Django 4.0.3 on 2022-06-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0019_purchaserequestaccounts_distribution_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequestaccounts',
            name='distribution_amount',
        ),
        migrations.RemoveField(
            model_name='purchaserequestaccounts',
            name='distribution_amount_currency',
        ),
        migrations.RemoveField(
            model_name='purchaserequestaccounts',
            name='distribution_percent',
        ),
        migrations.AddField(
            model_name='purchaserequestaccounts',
            name='distribution_input',
            field=models.FloatField(default=100),
        ),
    ]
