# Generated by Django 4.0.3 on 2022-05-19 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0021_purchaserequest_shipping_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='purchases.vendor'),
        ),
    ]
