# Generated by Django 4.0.3 on 2022-06-21 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0022_alter_balances_options_alter_ledgers_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledgers',
            name='purchase_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.purchaserequest', unique=True),
        ),
    ]
