# Generated by Django 4.0.3 on 2022-06-22 17:53

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_item_purchase_order_item_purchase_request'),
        ('purchases', '0025_rename_balances_balance_rename_ledgers_transaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderaccounts',
            name='accounts',
        ),
        migrations.RemoveField(
            model_name='purchaseorderaccounts',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='purchaseorderaccounts',
            name='spend_category',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitems',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitems',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='purchaseorderitems',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='purchaserequestitems',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchaserequestitems',
            name='purchase_request',
        ),
        migrations.RemoveField(
            model_name='purchaserequestitems',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='items',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='sales_tax_rate',
            field=models.DecimalField(decimal_places=3, default='.086', max_digits=5),
        ),
        migrations.AlterField(
            model_name='simpleproduct',
            name='extended_price',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='USD', max_digits=14),
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderAccounts',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderItems',
        ),
        migrations.DeleteModel(
            name='PurchaseRequestItems',
        ),
    ]
