# Generated by Django 4.0.3 on 2022-05-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0025_alter_purchaserequestaccounts_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.EmailField(max_length=60, null=True),
        ),
    ]
