# Generated by Django 4.0.3 on 2022-06-23 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0027_smartsheetrows'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SmartsheetRows',
        ),
    ]
