# Generated by Django 4.0.3 on 2022-05-23 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0027_unit_remove_purchaserequestitems_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequestitems',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='purchases.unit'),
        ),
    ]
