# Generated by Django 4.0.3 on 2022-06-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0028_delete_smartsheetrows'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentNumber',
            fields=[
                ('document', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('prefix', models.CharField(blank=True, max_length=10, null=True)),
                ('padding_digits', models.IntegerField(blank=True, null=True)),
                ('next_counter', models.IntegerField(default=1)),
                ('last_number', models.CharField(editable=False, max_length=50, null=True)),
            ],
        ),
    ]
