# Generated by Django 4.0.3 on 2022-05-23 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0030_purchaserequestitems_extended_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequestitems',
            name='extended_price',
        ),
        migrations.RemoveField(
            model_name='purchaserequestitems',
            name='extended_price_currency',
        ),
    ]
