# Generated by Django 4.0.3 on 2022-06-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0030_carrier_carrier_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='cost_center',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
