# Generated by Django 4.0.3 on 2022-07-21 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0031_accounts_cost_center'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'ordering': ['account_title'], 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='spendcategory',
            options={'ordering': ['code'], 'verbose_name_plural': 'Spend Categories'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('0', 'Wish List/Created'), ('1', 'Awaiting Approval'), ('2', 'Approved'), ('6', 'Ordered'), ('7', 'Shipped'), ('8', 'Received'), ('3', 'Complete'), ('4', 'Denied (no resubmission)'), ('5', 'Returned (please resubmit)')], default='0', max_length=150),
        ),
        migrations.AlterField(
            model_name='purchaserequestaccounts',
            name='purchase_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.purchaserequest'),
        ),
        migrations.AlterField(
            model_name='state',
            name='abbreviation',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
