# Generated by Django 4.0.3 on 2022-05-23 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0031_remove_purchaserequestitems_extended_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='accounts',
        ),
        migrations.RemoveField(
            model_name='purchaserequest',
            name='items',
        ),
    ]
