# Generated by Django 4.0.3 on 2022-05-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0032_remove_purchaserequest_accounts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('note', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Urgencies',
            },
        ),
    ]
