# Generated by Django 4.0.3 on 2022-05-24 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0033_urgency'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='urgency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='purchases.urgency'),
        ),
    ]
