# Generated by Django 4.0.3 on 2022-07-26 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0033_alter_purchaserequest_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackingEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_utc", models.DateTimeField()),
                ("description", models.TextField(max_length=150, null=True)),
                ("location", models.CharField(max_length=100)),
                ("stage", models.CharField(max_length=50)),
                (
                    "tracker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="purchases.tracker",
                    ),
                ),
            ],
        ),
    ]
