# Generated by Django 4.0.3 on 2022-07-26 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0035_alter_trackingevent_stage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaserequest",
            name="carrier",
        ),
        migrations.RemoveField(
            model_name="purchaserequest",
            name="tracker",
        ),
        migrations.RemoveField(
            model_name="purchaserequest",
            name="tracking_number",
        ),
        migrations.AddField(
            model_name="tracker",
            name="purchase_request",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="purchases.purchaserequest",
            ),
        ),
    ]
