# Generated by Django 4.0.3 on 2022-05-27 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0036_alter_purchaserequestaccounts_distribution_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='items',
            field=models.ManyToManyField(through='purchases.PurchaseRequestItems', to='purchases.product'),
        ),
    ]
