# Generated by Django 4.0.3 on 2022-07-29 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0037_alter_trackingevent_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trackingevent',
            options={'get_latest_by': ['time_utc'], 'ordering': ['-time_utc']},
        ),
        migrations.AddConstraint(
            model_name='simpleproduct',
            constraint=models.UniqueConstraint(fields=('purchase_request', 'identifier', 'name'), name='unique_purchase_request_part_number'),
        ),
        migrations.AddConstraint(
            model_name='tracker',
            constraint=models.UniqueConstraint(fields=('tracking_number', 'carrier'), name='unique_tracking_number_carrier'),
        ),
    ]
