# Generated by Django 4.0.3 on 2022-08-01 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0038_alter_trackingevent_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackerMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stage_key",
                    models.CharField(
                        help_text="Response Code", max_length=30, unique=True
                    ),
                ),
                ("stage", models.CharField(help_text="Friendly Text", max_length=30)),
                (
                    "rank",
                    models.PositiveIntegerField(help_text="Lowest First", unique=True),
                ),
            ],
        ),
        migrations.AddField(
            model_name="trackingevent",
            name="milestone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="purchases.trackermilestone",
            ),
        ),
    ]
