# Generated by Django 4.0.3 on 2022-06-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0039_alter_purchaseorderitems_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('0', 'Created'), ('1', 'Ordered'), ('2', 'Shipped'), ('3', 'Recieved'), ('4', 'Changed Required')], default='created', max_length=150),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('0', 'Wish List/Created'), ('1', 'Awaiting Approval'), ('2', 'Approved, Awaiting PO Creation'), ('3', 'Complete'), ('4', 'Denied (no resubmission)'), ('5', 'Returned (please resubmit)')], default='wish_list', max_length=150),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
