# Generated by Django 4.0.3 on 2022-08-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0040_remove_trackingevent_milestone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='events_hash',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
    ]
