# Generated by Django 4.0.3 on 2022-08-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0041_tracker_events_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='sub_status',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
    ]
