# Generated by Django 4.0.3 on 2022-08-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_item_product'),
        ('purchases', '0042_tracker_sub_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleproduct',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Manufacturer (optional)'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
