# Generated by Django 4.0.3 on 2022-08-22 20:11

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0043_simpleproduct_manufacturer_delete_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tracker',
            options={'ordering': ['-earliest_event_time']},
        ),
        migrations.AlterModelManagers(
            name='tracker',
            managers=[
                ('objects_ordered', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='tracker',
            name='earliest_event_time',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='trackingevent',
            name='stage',
            field=models.CharField(blank=True, default='', max_length=50),
            preserve_default=False,
        ),
    ]
