# Generated by Django 4.0.3 on 2022-08-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0044_alter_tracker_options_alter_tracker_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingevent',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
