# Generated by Django 4.0.3 on 2022-08-22 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0045_alter_trackingevent_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingevent',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
