# Generated by Django 4.0.3 on 2022-08-22 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0046_alter_trackingevent_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingevent',
            name='stage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
