# Generated by Django 4.0.3 on 2022-08-24 18:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0048_alter_tracker_managers_alter_carrier_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="manufacturer",
            name="slug",
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="vendor",
            name="slug",
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
