# Generated by Django 4.0.3 on 2022-08-24 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0049_vendor_created_date_alter_manufacturer_created_date_and_more'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE `seas_purchasing`.`purchases_accounts` DROP COLUMN `created_date`;"),
        migrations.RunSQL("ALTER TABLE `seas_purchasing`.`purchases_accounts` DROP COLUMN `slug`;"),
        # migrations.RunSQL("ALTER TABLE `seas_purchasing`.`purchases_carrier` DROP COLUMN `created_date`;"),
        # migrations.RunSQL("ALTER TABLE `seas_purchasing`.`purchases_spendcategory` DROP COLUMN `created_date`;"),
        # migrations.RunSQL("ALTER TABLE `seas_purchasing`.`purchases_spendcategory` DROP COLUMN `slug`;"),
    ]
