# Generated by Django 4.0.3 on 2022-08-24 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0050_auto_20220824_1246'),
    ]

    operations = [
        # migrations.RunSQL("ALTER TABLE `seas_purchasing`.`purchases_accounts` DROP COLUMN `created_date`;"),
        # migrations.RunSQL("ALTER TABLE `seas_purchasing`.`purchases_accounts` DROP COLUMN `slug`;"),
    ]
