# Generated by Django 4.0.3 on 2022-08-24 19:48

from django.db import migrations, models
import django.utils.timezone
from django.utils.text import slugify

def create_account_slugs(apps, schema_editor):
    Accounts = apps.get_model("purchases", "Accounts")
    accounts = Accounts.objects.all()
    for account in accounts:
        if not account.slug:
            if account.program_workday:
                return "{0.program_workday} ({0.account_title})".format(account)
            elif account.grant:
                return "%s (%s)" % (account.grant,account.account_title)
            elif account.gift:
                return "%s (%s)" % (account.gift,account.account_title)
            elif account.account_title:
                return account.account_title
            else:
                account.description


    count = Accounts.objects.bulk_update(accounts, ['slug'], 100)

class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0057_auto_20220824_1305'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE `seas_purchasing`.`purchases_accounts` DROP COLUMN `slug`;"),        
        # migrations.RemoveField(
        #     model_name = 'accounts',
        #     name = 'created_date',
        # ),
        # migrations.AddField(
        #     model_name='accounts',
        #     name='created_date',
        #     field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
        #     preserve_default=False,
        # ),
        migrations.AddField(
            model_name='accounts',
            name='slug',
            field=models.SlugField(editable=False),
            preserve_default=False,
        ),
        migrations.RunPython(create_account_slugs, migrations.RunPython.noop),
        # migrations.AlterField(
        #     model_name='accounts',
        #     name='slug',
        #     field=models.SlugField(editable=False, unique=True),
        # ),
    ]
