# Generated by Django 4.0.3 on 2022-08-24 21:02

from django.db import migrations, models
import django.utils.timezone
from django.utils.text import slugify
import random, string

def create_slugs(apps, app_name, model_name):
    model = apps.get_model(app_name, model_name)
    objects = model.objects.all()
    for object in objects:
        if not object.slug:
            if hasattr(object, 'name'):
                slug_raw = "{0.name}".format(object)
            elif hasattr(object, 'program_workday'):
                slug_raw = "{0.program_workday}".format(object)
            elif hasattr(object, "grant"):
                slug_raw = "{0.grant}".format(object)
            elif hasattr(object, "gift"):
                slug_raw = "{0.gift}".format(object)
            elif hasattr(object, "description"):
                slug_raw = "{0.description}".format(object)
            else:
                slug_raw = random.choices(string.ascii_lowercase + string.digits, k=8)

            object.slug = slugify(slug_raw, allow_unicode=True)

    return model, objects

def create_account_slugs(apps, schema_editor):
    model, accounts = create_slugs(apps, 'purchases', 'Accounts')

    count = model.objects.bulk_update(accounts, ['slug'], 100)
    print("{} accounts got a slug!".format(count))

def create_spend_category_slugs(apps, schema_editor):
    model, objects = create_slugs(apps, 'purchases', 'SpendCategory')

    count = model.objects.bulk_update(objects, ['slug'], 100)
    print("{} spend categories got a slug!".format(count))


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0056_accounts_created_date_accounts_slug'),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE `seas_purchasing`.`purchases_spendcategory` DROP COLUMN `slug`;"),
        migrations.RemoveField(
            model_name='accounts',
            name='slug',
        ),
        migrations.AddField(
            model_name='accounts',
            name='slug',
            field=models.SlugField(editable=False, unique=False),
            preserve_default = True,
        ),
        migrations.RunPython(create_account_slugs),
        # migrations.RunSQL("ALTER TABLE `seas_purchasing`.`purchases_accounts` DROP COLUMN `slug`;"),
        # migrations.AddField(
        #     model_name='accounts',
        #     name='created_date',
        #     field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='carrier',
        #     name='created_date',
        #     field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='spendcategory',
        #     name='created_date',
        #     field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
        #     preserve_default=False,
        # ),
        migrations.AddField(
            model_name='spendcategory',
            name='slug',
            field=models.SlugField(editable=False),
            preserve_default=False,
        ),
        migrations.RunPython(create_spend_category_slugs),
        migrations.AlterField(
            model_name='carrier',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='carrier',
            name='slug',
            field=models.SlugField(editable=False),
            preserve_default=False,
        ),
    ]
