# Generated by Django 4.0.3 on 2022-08-24 21:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0057_accounts_created_date_carrier_created_date_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE `seas_purchasing`.`purchases_accounts` DROP COLUMN `created_date`;"
        ),
        migrations.RunSQL(
            "ALTER TABLE `seas_purchasing`.`purchases_carrier` DROP COLUMN `created_date`;"
        ),
        migrations.RunSQL(
            "ALTER TABLE `seas_purchasing`.`purchases_spendcategory` DROP COLUMN `created_date`;"
        ),
        migrations.AddField(
            model_name="accounts",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="carrier",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="spendcategory",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        # migrations.AlterField(
        #     model_name='accounts',
        #     name='slug',
        #     field=models.SlugField(editable=False, unique=True),
        # ),
        # migrations.AlterField(
        #     model_name='carrier',
        #     name='slug',
        #     field=models.SlugField(editable=False, unique=True),
        # ),
        migrations.AlterField(
            model_name="spendcategory",
            name="slug",
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
