# Generated by Django 4.0.3 on 2022-08-24 21:35

import random
import string

from django.db import migrations, models
from django.utils.text import slugify


def create_slugs(apps, app_name, model_name):
    model = apps.get_model(app_name, model_name)
    objects = model.objects.all()
    for object in objects:
        if hasattr(object, "name"):
            slug_raw = f"{object.name}"
        elif hasattr(object, "program_workday"):
            slug_raw = f"{object.program_workday}"
        elif hasattr(object, "grant"):
            slug_raw = f"{object.grant}"
            print(slug_raw)
        elif hasattr(object, "gift"):
            slug_raw = f"{object.gift}"
        elif hasattr(object, "description"):
            slug_raw = f"{object.description}"
        else:
            slug_raw = random.choices(string.ascii_lowercase + string.digits, k=8)

        object.slug = slugify(slug_raw, allow_unicode=True)

    return model, objects


def create_account_slugs(apps, schema_editor):
    model, accounts = create_slugs(apps, "purchases", "Accounts")

    count = model.objects.bulk_update(accounts, ["slug"], 100)
    print(f"{count} accounts got a slug!")


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0058_accounts_created_date_carrier_created_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accounts",
            name="slug",
        ),
        migrations.AddField(
            model_name="accounts",
            name="slug",
            field=models.SlugField(editable=False, unique=False),
            preserve_default=True,
        ),
        # migrations.RunPython(create_account_slugs),
        # migrations.AlterField(
        #     model_name="accounts",
        #     name="slug",
        #     field=models.SlugField(unique=True),
        # ),
    ]
