# Generated by Django 4.0.3 on 2022-08-24 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0059_auto_20220824_1435'),
    ]

    operations = [
    ]
