# Generated by Django 4.0.3 on 2022-10-18 19:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "purchases",
            "0061_auto_20220824_1450_squashed_0127_remove_purchaserequest_gravatar_email",  # noqa: E501
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="accounts",
            options={"ordering": ["account_title"], "verbose_name_plural": "Accounts"},
        ),
        migrations.AddField(
            model_name="accounts", name="slug", field=models.SlugField()
        ),
        migrations.RemoveField(
            model_name="accounts",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="purchaserequest",
            name="new_st",
        ),
        migrations.AddField(
            model_name="accounts",
            name="cost_center",
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="carrier",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="spendcategory",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="spendcategory",
            name="slug",
            field=models.SlugField(default="test", editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="carrier",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="simpleproduct",
            name="rank",
            field=models.SmallIntegerField(
                editable=False, verbose_name="in pr ordering"
            ),
        ),
    ]
