# Generated by Django 4.0.3 on 2022-08-24 22:02

from django.db import migrations, models
from django.utils.text import slugify
import random, string

def create_slugs(apps, app_name, model_name):
    print_string = []
    model = apps.get_model(app_name, model_name)
    print_string.append("\nModel: {}".format(model))
    objects = model.objects.all()
    print_string.append("First object: {} | Total Objects: {}".format(objects.first(), len(objects)))
    print(print_string)
    for counter, object in enumerate(objects):
        obj_print_str = ["Object[{}]: {}".format(counter, object)]
        if hasattr(object, 'name') and object.name:
            slug_raw = "{0.name}".format(object)
            obj_print_str.append("name -> {}".format(slug_raw))
        elif hasattr(object, 'program_workday') and object.program_workday:
            slug_raw = "{0.program_workday}".format(object)
            obj_print_str.append("program_workday -> {}".format(slug_raw))
        elif hasattr(object, 'grant') and object.grant:
            slug_raw = "{0.grant}".format(object)
            obj_print_str.append("grant -> {}".format(slug_raw))
        elif hasattr(object, 'gift') and object.gift:
            slug_raw = "{0.gift}".format(object)
            obj_print_str.append("gift -> {}".format(slug_raw))
        elif hasattr(object, "description") and object.description:
            slug_raw = "{0.description}".format(object)
            obj_print_str.append("description -> {}".format(slug_raw))
        else:
            slug_raw = random.choices(string.ascii_lowercase + string.digits, k=8)
            obj_print_str.append("random -> {}".format(slug_raw))

        object.slug = slugify(slug_raw, allow_unicode=True)
        obj_print_str.append("-> {}".format(object.slug))
        print(obj_print_str)

    return model, objects

def create_carrier_slugs(apps, schema_editor):
    model, objects = create_slugs(apps, 'purchases', 'Carrier')

    count = model.objects.bulk_update(objects, ['slug'], 100)
    print("{} carriers got a slug!".format(count))


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0061_auto_20220824_1450'),
    ]

    operations = [
        migrations.RunPython(create_carrier_slugs),
        migrations.AlterField(
            model_name='accounts',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
