# Generated by Django 4.0.3 on 2022-10-19 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "purchases",
            "0061_auto_20220824_1450_squashed_0127_remove_purchaserequest_gravatar_email",  # noqa: E501
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaserequest",
            name="new_st",
        ),
    ]
