# Generated by Django 4.0.3 on 2022-10-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "purchases",
            "0062_remove_accounts_slug_remove_purchaserequest_new_st_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tracker",
            name="note",
            field=models.TextField(
                blank=True, help_text="which items, how many, etc.", verbose_name="note"
            ),
        ),
        migrations.AddField(
            model_name="requisitioner",
            name="gravatar_email",
            field=models.EmailField(
                "gravatar email", max_length=254, default="test@test.com"
            ),
            preserve_default=False,
        ),
    ]
