# Generated by Django 4.0.3 on 2022-10-19 20:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "purchases",
            "0062_remove_accounts_slug_remove_purchaserequest_new_st_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="carrier",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="spendcategory",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="spendcategory",
            name="slug",
            field=models.SlugField(default="test", editable=False, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="carrier",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="simpleproduct",
            name="rank",
            field=models.SmallIntegerField(
                editable=False, verbose_name="in pr ordering"
            ),
        ),
    ]
