# Generated by Django 4.0.3 on 2022-08-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0062_alter_accounts_slug_alter_carrier_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='slug',
            field=models.SlugField(editable=False, unique=True)
        )
    ]
