# Generated by Django 4.0.3 on 2022-10-21 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0063_tracker_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisitioner',
            name='gravatar_email',
        ),
    ]
