# Generated by Django 4.0.3 on 2022-10-19 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0063_auto_20221019_1303'),
        ('purchases', 'migration_tools'),
    ]

    operations = [
    ]
