# Generated by Django 4.0.3 on 2022-08-24 22:22

import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0063_auto_20220824_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=True,
        )
    ]
