# Generated by Django 4.0.8 on 2022-11-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0064_remove_requisitioner_gravatar_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['sort_column', 'name']},
        ),
        migrations.AddField(
            model_name='vendor',
            name='sort_column',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
    ]
