# Generated by Django 4.0.8 on 2022-11-22 17:06

from django.db import migrations

from web_project.helpers import sort_title


def create_sort_title(apps, schema):
    Vendor = apps.get_model("purchases", "Vendor")
    qs = Vendor.objects.all()

    for object in qs:
        object.sort_column = sort_title(object.name)

    Vendor.objects.bulk_update(qs, ["sort_column"])

    # Manufacturer.objects.bulk_update(qs, ["slug"])


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0065_alter_vendor_options_vendor_sort_column"),
    ]

    operations = [
        migrations.RunPython(create_sort_title),
    ]
