# Generated by Django 4.0.3 on 2022-08-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0065_documentnumber_last_generated_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='sales_tax_rate',
            field=models.DecimalField(decimal_places=5, default='.087', max_digits=10),
        ),
        migrations.AlterField(
            model_name='simpleproduct',
            name='unit_price',
            field=models.DecimalField(decimal_places=4, max_digits=14),
        ),
    ]
