# Generated by Django 4.0.8 on 2022-11-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0066_auto_20221122_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendororder',
            name='notes',
            field=models.TextField(blank=True, help_text="what has or hasn't been received, etc.", verbose_name='notes'),
        ),
    ]
