# Generated by Django 4.0.3 on 2022-09-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0066_alter_purchaserequest_sales_tax_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
