# Generated by Django 4.0.8 on 2023-01-19 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0068_alter_tracker_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisitioner',
            options={'ordering': ['user__last_name', 'user__first_name']},
        ),
        migrations.AlterModelOptions(
            name='tracker',
            options={'ordering': ['-earliest_event_time', '-purchase_request__number']},
        ),
    ]
