# Generated by Django 4.0.3 on 2022-09-06 17:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0069_vendororder_sales_tax_vendororder_sales_tax_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendororder',
            name='invoice_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='invoice due date'),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='invoice number'),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='order_placed',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date order placed'),
            preserve_default=False,
        ),
    ]
