# Generated by Django 4.0.8 on 2023-01-19 23:22

from django.db import migrations


def create_first_event_time(apps, schema):
    Tracker = apps.get_model("purchases", "Tracker")
    qs = Tracker.objects.all()
    for t in qs:
        try:
            t.earliest_event_time = t.trackingevent_set.earliest().time_utc
        except Exception as e:
            print(f"{t.str} has no earliest event. | {e}")

    Tracker.objects.bulk_update(qs, ["earliest_event_time"])


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0069_alter_requisitioner_options_alter_tracker_options"),
    ]

    operations = [
        migrations.RunPython(code=create_first_event_time),
    ]
