# Generated by Django 4.0.3 on 2022-09-06 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0070_vendororder_invoice_due_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackerItems",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=3,
                        max_digits=15,
                        verbose_name="quantity in shipment",
                    ),
                ),
                ("missing", models.BooleanField(default=False, verbose_name="missing")),
                (
                    "simple_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="purchases.simpleproduct",
                        verbose_name="item",
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="vendororder",
            options={
                "ordering": ["-order_placed", "-created_date"],
                "verbose_name": "vendor order",
                "verbose_name_plural": "vendor orders",
            },
        ),
        migrations.AddField(
            model_name="tracker",
            name="received",
            field=models.BooleanField(default=False, verbose_name="package received"),
        ),
        migrations.AddField(
            model_name="tracker",
            name="simple_products",
            field=models.ManyToManyField(
                through="purchases.TrackerItems",
                to="purchases.simpleproduct",
                verbose_name="items",
            ),
        ),
        migrations.AlterField(
            model_name="vendororder",
            name="link",
            field=models.URLField(blank=True, verbose_name="link"),
        ),
        migrations.AlterField(
            model_name="vendororder",
            name="order_placed",
            field=models.DateField(blank=True, verbose_name="date order placed"),
        ),
        migrations.AddField(
            model_name="trackeritems",
            name="tracker",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="purchases.tracker",
                verbose_name="tracker",
            ),
        ),
    ]
