# Generated by Django 4.0.8 on 2023-02-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0070_auto_20230119_1522'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accounts',
            name='unique_account',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='budget_code',
            field=models.CharField(blank=True, help_text='usually first four characters of account', max_length=5, verbose_name='budget code'),
        ),
    ]
