# Generated by Django 4.0.8 on 2023-02-08 17:30

from django.db import migrations, models
import django.utils.timezone

from .migration_tools import create_account_slugs


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0071_remove_accounts_unique_account_and_more"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name="accounts",
        #     name="slug",
        #     field=models.SlugField(null=True, editable=False, unique=True),
        # ),
        migrations.RunPython(create_account_slugs),
        migrations.AlterField(
            model_name="accounts",
            name="slug",
            field=models.SlugField(null=False, editable=False, unique=True),
        ),
    ]
