# Generated by Django 4.0.10 on 2023-04-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0071_remove_accounts_unique_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendororder',
            name='reconciled',
            field=models.BooleanField(default=False, verbose_name='reconciled'),
        ),
    ]
