# Generated by Django 4.2.2 on 2023-06-08 20:40

from django.db import migrations
import web_project.fields


class Migration(migrations.Migration):
    dependencies = [
        ("purchases", "0072_vendororder_reconciled"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaserequest",
            name="sales_tax_rate",
            field=web_project.fields.SimplePercentageField(
                decimal_places=4,
                max_digits=10,
                null=True,
                verbose_name="sales tax rate",
            ),
        ),
    ]
