# Generated by Django 4.0.3 on 2022-09-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0072_rename_trackeritems_trackeritem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracker',
            old_name='simple_products',
            new_name='simple_product',
        ),
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='group name')),
                ('accounts', models.ManyToManyField(to='purchases.accounts', verbose_name='accounts')),
            ],
            options={
                'verbose_name_plural': 'account groups',
                'ordering': ['name'],
            },
        ),
    ]
