# Generated by Django 4.0.3 on 2022-09-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0073_rename_simple_products_tracker_simple_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerStatusSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracker_status', models.CharField(max_length=50, verbose_name='status')),
                ('rank', models.PositiveSmallIntegerField(help_text='rank in sort order', unique=True, verbose_name='rank')),
            ],
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='purchase_type',
            field=models.CharField(choices=[('po', 'PURCHASE ORDER'), ('pcard', 'PCARD'), ('iri', 'IRI'), ('invoice voucher', 'INVOICE VOUCHER'), ('contract', 'CONTRACT')], default='pcard', max_length=25, verbose_name='Choose One'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.CharField(choices=[('0', 'created'), ('1', 'awaiting approval'), ('2', 'approved'), ('3', 'complete'), ('4', 'denied (no resubmission)'), ('5', 'returned (please resubmit'), ('6', 'ordered'), ('7', 'shipped'), ('8', 'received'), ('9', 'partial')], default='0', max_length=150),
        ),
    ]
