# Generated by Django 4.0.3 on 2022-09-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0075_remove_accounts_fund_alter_accounts_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='account',
            field=models.CharField(help_text='in form XXXX-XXXX.', max_length=10, verbose_name='account'),
        ),
    ]
