# Generated by Django 4.0.3 on 2022-09-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0076_alter_accounts_account'),
    ]

    operations = [
        migrations.AddField(
            model_name="accounts",
            name="slug",
            field=models.SlugField(),
        ),
        # migrations.RemoveField(
        #     model_name='accounts',
        #     name='slug',
        # ),
        # migrations.AlterField(
        #     model_name='accounts',
        #     name='account',
        #     field=models.CharField(unique=False),
        # ),
        # migrations.AlterField(
        #     model_name='accounts',
        #     name='account',
        #     field=models.CharField(help_text='in form XXXX-XXXX.', max_length=10, unique=True, verbose_name='account'),
        # ),
    ]
