# Generated by Django 4.0.3 on 2022-09-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0077_remove_accounts_slug_alter_accounts_account'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='accounts',
        #     name='slug',
        # ),
        migrations.AlterField(
            model_name='accounts',
            name='account',
            field=models.CharField(help_text='in form XXXX-XXXX.', max_length=10, unique=False, verbose_name='account'),
        ),
        # migrations.AlterField(
        #     model_name='accounts',
        #     name='account',
        #     field=models.CharField(help_text='in form XXXX-XXXX.', max_length=10, unique=True, verbose_name='account'),
        # ),
    ]
