# Generated by Django 4.0.3 on 2022-09-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0078_auto_20220912_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.RemoveField(
            model_name='accounts',
            name='slug',
        ),
    ]
