# Generated by Django 4.0.3 on 2022-09-14 17:23

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0080_accounts_test_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "rank",
                    models.PositiveSmallIntegerField(
                        editable=False, verbose_name="rank"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        choices=[("PR", "Purchase Request"), ("OR", "Order")],
                        max_length=30,
                        verbose_name="model",
                    ),
                ),
            ],
            options={
                "verbose_name": "status",
                "verbose_name_plural": "statuses",
                "ordering": ["rank"],
            },
        ),
        migrations.AddConstraint(
            model_name="status",
            constraint=models.UniqueConstraint(
                django.db.models.expressions.F("model"),
                django.db.models.expressions.F("rank"),
                name="status_model_unique",
            ),
        ),
    ]
