# Generated by Django 4.0.3 on 2022-09-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0081_status_status_status_model_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='status',
            name='status_model_unique',
        ),
        migrations.AddConstraint(
            model_name='status',
            constraint=models.UniqueConstraint(fields=('model', 'rank'), name='status_model_unique'),
        ),
    ]
