# Generated by Django 4.0.3 on 2022-09-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0082_remove_status_status_model_unique_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['parent_model', 'rank'], 'verbose_name': 'status', 'verbose_name_plural': 'statuses'},
        ),
        migrations.RemoveConstraint(
            model_name='status',
            name='status_model_unique',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='model',
            new_name='parent_model',
        ),
        migrations.AddConstraint(
            model_name='status',
            constraint=models.UniqueConstraint(fields=('parent_model', 'rank'), name='status_model_unique'),
        ),
    ]
