# Generated by Django 4.0.3 on 2022-09-15 15:40

import django.db.models.deletion
from django.db import migrations, models

MATCH = {
    "0": "Created",
    "1": "Awaiting Approval",
    "6": "Ordered",
    "2": "Approved",
    "7": "Shipped",
    "9": "Partially Received",
    "8": "Received",
}


def fill_status_fk(apps, schema_editor):
    PurchaseRequest = apps.get_model("purchases", "PurchaseRequest")
    Status = apps.get_model("purchases", "Status")
    qs = PurchaseRequest.objects.all()
    for request in qs:
        old_status = request.status
        new_status_name = MATCH[old_status]
        print(f"New name: {new_status_name}")
        request.status_fk, _ = Status.objects.get_or_create(name=new_status_name)
        print(
            "New status[{}]: {}[{}]".format(
                request.number, request.status_fk.name, request.status_fk.rank
            )
        )

    PurchaseRequest.objects.bulk_update(qs, ["status_fk"])


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0083_alter_status_options_and_more"),
    ]

    operations = [
        # migrations.RunSQL(
        #     "DROP INDEX `purchases_purchasere_status_fk_id_4916f867_fk_purchases` ON `seas_purchasing`.`purchases_purchaserequest`"  # noqa: E501
        # ),
        # migrations.RunSQL(
        #     "ALTER TABLE `seas_purchasing`.`purchases_purchaserequest` DROP INDEX `purchases_purchasere_status_fk_id_4916f867_fk_purchases`"  # noqa: E501
        # ),
        # migrations.RunSQL(
        #     "ALTER TABLE `seas_purchasing`.`purchases_purchaserequest` DROP FOREIGN KEY `purchases_purchasere_status_fk_id_4916f867_fk_purchases`;"  # noqa: E501
        # ),
        # migrations.RunSQL(
        #     "ALTER TABLE `seas_purchasing`.`purchases_purchaserequest` DROP COLUMN `status_fk_id`;"  # noqa: E501
        # ),
        migrations.RemoveField(
            model_name="purchaserequest",
            name="status",
        ),
        migrations.AddField(
            model_name="purchaserequest",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="purchases.status",
            ),
        ),
        # migrations.RunPython(fill_status_fk),
        # migrations.RenameField(
        #     model_name="purchaserequest",
        #     old_name="status",
        #     new_name="status_choices",
        # ),
        # migrations.RenameField(
        #     model_name="purchaserequest",
        #     old_name="status_fk",
        #     new_name="status",
        # ),
    ]
