# Generated by Django 4.0.3 on 2022-09-15 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0084_purchaserequest_status_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='status_choices',
        ),
        migrations.AddField(
            model_name='status',
            name='open',
            field=models.BooleanField(default=False, help_text='purchase request not complete', verbose_name='open'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='purchases.status'),
        ),
    ]
