# Generated by Django 4.0.3 on 2022-09-15 17:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "purchases",
            "0085_remove_purchaserequest_status_choices_status_open_and_more",
        ),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE `seas_purchasing`.`purchases_manufacturer` DROP COLUMN `slugger`;"
        ),
        migrations.AddField(
            model_name="manufacturer",
            name="slug",
            field=models.SlugField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
