# Generated by Django 4.0.3 on 2022-09-19 23:14

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0087_manufacturer_created_date_custom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackeritem',
            name='simple_product',
        ),
        migrations.RemoveField(
            model_name='trackeritem',
            name='tracker',
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='simple_product',
        ),
        migrations.AddConstraint(
            model_name='accounts',
            constraint=models.UniqueConstraint(django.db.models.expressions.F('gift'), django.db.models.expressions.F('grant'), django.db.models.expressions.F('program_workday'), name='unique_program'),
        ),
        migrations.AddConstraint(
            model_name='accounts',
            constraint=models.UniqueConstraint(django.db.models.expressions.F('account'), name='unique_account'),
        ),
        migrations.DeleteModel(
            name='TrackerItem',
        ),
    ]
