# Generated by Django 4.0.3 on 2022-09-19 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0088_remove_trackeritem_simple_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
