# Generated by Django 4.0.3 on 2022-09-26 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0094_alter_vendor_discount_percentage'),
    ]

    operations = [
    ]
