# Generated by Django 4.0.3 on 2022-09-26 19:01

from django.db import migrations, models

import web_project.fields


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0095_purchaserequestaccount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='instruction',
            field=models.TextField(verbose_name='Special Instructions'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='sales_tax_rate',
            field=web_project.fields.PercentageField(decimal_places=6, max_digits=10),
        ),
    ]
