# Generated by Django 4.0.3 on 2022-09-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0096_alter_purchaserequest_instruction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='sales_tax_rate',
            field=models.FloatField(),
        ),
    ]
