# Generated by Django 4.0.3 on 2022-09-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0097_alter_purchaserequest_sales_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='sales_tax_rate',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
