# Generated by Django 4.0.3 on 2022-09-26 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # ('accounts', '0005_auto_20220926_1632'),
        ('purchases', '0099_auto_20220926_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequestaccount',
            name='spend_category_ext',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.spendcategory'),
        ),
    ]
