# Generated by Django 4.0.3 on 2022-09-26 23:51

from django.db import migrations
from django.db.models import OuterRef, Subquery


def populate_spendcat_ext(apps, schema_editor):
    PurchaseRequestAccount = apps.get_model("purchases", "purchaserequestaccount")
    ExternalSpendCategory = apps.get_model("accounts", "spendcategory")
    SpendCategory = apps.get_model("purchases", "spendcategory")

    qs = PurchaseRequestAccount.objects.all()

    # pseudo-code
    """qs.update(
        spend_category_ext = spend_category
    )"""

    # real code
    scsq = SpendCategory.objects.filter(id = OuterRef(OuterRef("spend_category_id")))
    escsq = ExternalSpendCategory.objects.filter(name__in=Subquery(scsq.values("code")))

    qs.update(
        spend_category_ext_id = Subquery(escsq.values("id")[:1])
    )

    new_name = PurchaseRequestAccount.objects.first().spend_category_ext.name
    print(f"Name: {new_name}")


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0100_purchaserequestaccount_spend_category_ext'),
        ('accounts', '0005_auto_20220926_1632'),
    ]

    operations = [
        migrations.RunPython(populate_spendcat_ext),
    ]
