# Generated by Django 4.0.3 on 2022-09-29 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0101_auto_20220926_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='accounts',
        ),
    ]
