# Generated by Django 4.0.3 on 2022-09-29 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_spendcategory'),
        ('purchases', '0102_remove_purchaserequest_accounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequestaccount',
            name='spend_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='purchases.spendcategory'),
        ),
        migrations.AlterField(
            model_name='purchaserequestaccount',
            name='spend_category_ext',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='accounts.spendcategory'),
            preserve_default=False,
        ),
    ]
