# Generated by Django 4.0.3 on 2022-09-29 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0103_alter_purchaserequestaccount_spend_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequestaccount',
            name='spend_category',
        ),
    ]
