# Generated by Django 4.0.3 on 2022-10-03 15:25

from django.db import migrations

import web_project.fields


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0108_alter_purchaserequest_sales_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='sales_tax_rate',
            field=web_project.fields.PercentageField(decimal_places=6, max_digits=10),
        ),
    ]
