# Generated by Django 4.0.3 on 2022-10-05 23:41

from django.db import migrations, models

import web_project.fields


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0109_alter_purchaserequest_sales_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleproduct',
            name='taxable',
            field=models.BooleanField(default=True, verbose_name='taxable'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='sales_tax_rate',
            field=web_project.fields.PercentageField(decimal_places=6, max_digits=10),
        ),
    ]
