# Generated by Django 4.0.3 on 2022-10-07 18:56

from django.db import migrations

import web_project.fields


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0112_alter_purchaserequest_sales_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='new_tax_rate',
            field=web_project.fields.PercentageField(field_decimal_places=6, default=.087, max_digits=10),
        ),
    ]
