# Generated by Django 4.0.3 on 2022-10-07 19:05

from django.db import migrations

import web_project.fields


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0114_alter_purchaserequest_new_tax_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='new_tax_rate',
        ),
    ]
