# Generated by Django 4.0.3 on 2022-10-10 18:41

from django.db import migrations

import web_project.fields


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0116_alter_purchaserequest_sales_tax_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='sales_tax_rate',
            field=web_project.fields.PercentageField(decimal_places=4, max_digits=10),
        ),
    ]
