# Generated by Django 4.0.3 on 2022-10-10 21:41

from django.db import migrations, models
from django.utils.translation import gettext_lazy as _

import web_project.fields


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0117_alter_purchaserequest_sales_tax_rate'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='purchaserequest',
        #     name='sales_tax_rate',
        # ),
        migrations.AddField(
            model_name='purchaserequest',
            name='new_st',
            field=models.DecimalField(_("sales tax rate"), max_digits=10, decimal_places=4, default=0.087),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='discount_percentage',
            field=web_project.fields.PercentageField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
