# Generated by Django 4.0.3 on 2022-10-10 21:48

from django.db import migrations

import web_project.fields


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0119_remove_purchaserequest_new_st_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='sales_tax_rate',
            field=web_project.fields.SimplePercentageField(decimal_places=4, max_digits=10, null=True, verbose_name='sales tax rate'),
        ),
    ]
