# Generated by Django 4.0.3 on 2022-10-10 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0120_purchaserequest_sales_tax_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequest',
            name='sales_tax_rate',
            field=models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='sales tax rate'),
        ),
    ]
