# Generated by Django 4.0.3 on 2022-10-10 22:28

from django.db import migrations

import web_project.fields


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0121_alter_purchaserequest_sales_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='new_st',
            field=web_project.fields.SimplePercentageField(decimal_places=4, max_digits=10, null=True, verbose_name='new sales tax'),
        ),
    ]
