# Generated by Django 4.0.3 on 2022-10-13 23:15

from django.db import migrations, models
import django.core.validators


import purchases.models.models_data


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0123_remove_purchaserequest_new_st_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendororder",
            name="approved_request",
            field=models.FileField(
                blank=True,
                help_text="pdf",
                upload_to=purchases.models.models_data.vendor_order_attachments_path,
                validators=[
                    django.core.validators.FileExtensionValidator([".pdf", ".pdfa"])
                ],
                verbose_name="approved purchase request",
            ),
        ),
    ]
