# Generated by Django 4.0.3 on 2022-10-17 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0125_alter_vendororder_approved_request"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaserequest",
            name="gravatar_email",
            field=models.EmailField(blank=True),
        )
    ]
