# Generated by Django 4.0.3 on 2022-10-17 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0126_auto_20221017_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='gravatar_email',
        ),
    ]
