# Generated by Django 4.0.3 on 2022-09-26 21:35

from django.db import migrations
from django.db.models import F

from web_project.helpers import first_true


def change_account_foreign_relationship(apps, schema_editor):
    PurchaseRequest = apps.get_model("purchases", "purchaserequest")
    PurchaseRequestAccount = apps.get_model("purchases", "purchaserequestaccount")
    PurchaseRequestAccounts = apps.get_model("purchases", "purchaserequestaccounts")
    Account = apps.get_model("accounts", "account")

    MATCH = {
        "percent": "p",
        "amount": "a",
    }

    old_account_objs = PurchaseRequestAccounts.objects.all()

    for old_account in old_account_objs:
        old_account_obj = old_account.accounts
        identity_list = [old_account_obj.program_workday, old_account_obj.grant, old_account_obj.gift]
        account_identity = first_true(identity_list, False)
        new_account = Account.objects.get(fund = account_identity)
        PurchaseRequestAccount.objects.create(
            purchase_request = old_account.purchase_request,
            account = new_account,
            spend_category = old_account.spend_category,
            distribution_type = MATCH[old_account.distribution_type],
            distribution_input = old_account.distribution_input
        )


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0098_alter_purchaserequest_sales_tax_rate'),
    ]

    operations = [
        migrations.RunPython(change_account_foreign_relationship),
    ]
