# Generated by Django 4.0.3 on 2022-09-23 18:57

from django.db import migrations
from django.db.models import F
from django.utils.text import slugify


def correct_revision_slug(apps, schema_editor):
    PartRevision = apps.get_model("partnumbers", "partrevision")

    PartRevision.objects.update(
        slug = slugify("{} {}".format(F("part.number"), F("name")), allow_unicode=True)
    )


class Migration(migrations.Migration):

    dependencies = [
        ("partnumbers", '0001_initial'),
    ]

    operations = [
        migrations.RunPython(correct_revision_slug),
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['number']},
        ),
    ]
