# Generated by Django 4.0.3 on 2022-09-23 19:09

from django.db import migrations
from django.db.models import F

# from django.utils.text import slugify


def correct_revision_slug(apps, schema_editor):
    PartRevision = apps.get_model("partnumbers", "partrevision")

    PartRevision.objects.update(
        slug = F("part.number")
    )
    part1 = PartRevision.objects.all().first()
    print(f"{part1.slug}")


class Migration(migrations.Migration):

    dependencies = [
        ("partnumbers", '0002_alter_part_options'),
    ]

    operations = [
        migrations.RunPython(correct_revision_slug),
    ]
