# Generated by Django 4.0.3 on 2022-09-23 19:16

from django.db import migrations
from django.db.models import F

# from django.utils.text import slugify


def correct_revision_slug(apps, schema_editor):
    PartRevision = apps.get_model("partnumbers", "partrevision")
    Part = apps.get_model("partnumbers", "part")

    PartRevision.objects.update(
        slug = f'{Part.objects.get(pk=F("part")).name}-{F("name")}'
    )
    part1 = PartRevision.objects.all().first()
    print(f"{part1.slug}")


class Migration(migrations.Migration):

    dependencies = [
        ("partnumbers", '0004_auto_20220923_1211'),
    ]

    operations = [
        migrations.RunPython(correct_revision_slug),
    ]
