# Generated by Django 4.0.3 on 2022-09-23 20:12

from django.db import migrations

# from django.db.models import F, OuterRef, Subquery, Value
# from django.db.models.functions import Concat
from django.utils.text import slugify


def correct_revision_slug(apps, schema_editor):
    PartRevision = apps.get_model("partnumbers", "partrevision")
    Part = apps.get_model("partnumbers", "part")

    revisions = PartRevision.objects.all()

    for r in revisions:
        print(r.part.slug)
        slug_base = f'{r.part.slug} {r.name}'
        r.slug = slugify(slug_base, allow_unicode=True)
    partrev1 = PartRevision.objects.all().first()
    part1 = Part.objects.all().first()
    print()
    print(f"PartRevision.slug: {partrev1.slug}")
    print(f"PartRevision.part.slug: {partrev1.part.slug}")
    print(f"Part: {part1.slug}")


class Migration(migrations.Migration):

    dependencies = [
        ("partnumbers", '0013_auto_20220923_1310'),
    ]

    operations = [
        migrations.RunPython(correct_revision_slug),
    ]
