# Generated by Django 4.0.3 on 2022-09-21 19:30

import django.utils.timezone
import djmoney.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_auto_20220921_1043"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basetransaction",
            name="amount",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default_currency="USD",
                help_text="positive values decrease balance, negative increase",
                max_digits=14,
                verbose_name="amount",
            ),
        ),
        migrations.AlterField(
            model_name="basetransaction",
            name="date_time",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name="time and date that adjustment affects balance",
            ),
        ),
    ]
