# Generated by Django 4.2.2 on 2023-06-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_account_account_alter_account_budget_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="cost_center",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
