# Generated by Django 4.0.3 on 2022-05-26 17:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchases', '0036_alter_purchaserequestaccounts_distribution_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prefix', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tag_prefix', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=15)),
            ],
            options={
                'verbose_name_plural': 'Equipment Accessories',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(100)])),
                ('full_number', models.CharField(blank=True, max_length=15)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.building')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('equipment_tag', models.CharField(blank=True, max_length=30, null=True)),
                ('item_type', models.CharField(choices=[('accessory', 'Accessory'), ('consumable', 'Consumable'), ('equipment', 'Equipment')], default='equipment', max_length=30, verbose_name='Choose One')),
                ('accessory', models.ManyToManyField(through='inventory.EquipmentAccessory', to='inventory.item')),
                ('department', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.department')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.manufacturer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.product')),
            ],
        ),
        migrations.AddField(
            model_name='equipmentaccessory',
            name='accessory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_accessory', to='inventory.item'),
        ),
        migrations.AddField(
            model_name='equipmentaccessory',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='inventory.item'),
        ),
    ]
