# Generated by Django 4.0.3 on 2022-08-05 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_item_purchase_order_item_purchase_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='product',
        ),
    ]
